schema = 3

[mod]
[mod.'github.com/inconshreveable/mousetrap']
version = 'v1.1.0'
hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

[mod.'github.com/kr/pretty']
version = 'v0.3.1'
hash = 'sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU='

[mod.'github.com/rogpeppe/go-internal']
version = 'v1.14.1'
hash = 'sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E='

[mod.'github.com/spf13/cobra']
version = 'v1.10.2'
hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

[mod.'github.com/spf13/pflag']
version = 'v1.0.10'
hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

[mod.'golang.org/x/crypto']
version = 'v0.57.0'
hash = 'sha256-3/hkB+mZVBKnoxUaJv7DOzvxaL+8uQ7V6ofW4JiHhz4='

[mod.'golang.org/x/net']
version = 'v0.59.0'
hash = 'sha256-EGnbU9mIAvXqx4vEIWJDt+lZgs/YsUngAFJwmFSc5Tc='

[mod.'golang.org/x/sys']
version = 'v0.48.0'
hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='

[mod.'golang.zx2c4.com/wintun']
version = 'v0.0.0-20230126152724-0fa3db229ce2'
hash = 'sha256-cjMLNjKnnupVROWmeASORVieAL9ieYdzX3cFzG8bCpo='

[mod.'golang.zx2c4.com/wireguard']
version = 'v0.0.0-20260522210424-ecfc5a8d5446'
hash = 'sha256-qfF39wqSCUlsXsaJyjcnv9n8ZjRJfIKDo6i2DursedU='

[mod.'gopkg.in/check.v1']
version = 'v1.0.0-20201130134442-10cb98267c6c'
hash = 'sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs='

[mod.'gopkg.in/yaml.v3']
version = 'v3.0.1'
hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

[mod.'gvisor.dev/gvisor']
version = 'v0.0.0-20260815055033-7d8fb7f28de4'
hash = 'sha256-qNul+ILbeffSiOxFoVeNtayahFZVp+/W2YIJf53Hfc8='
